# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true # removing permalinks for Jekyll v3.0

# Setup
title:               Hubert.World
tagline:             "Sharing with you, World :)"
description:         "Sharing with you experiences, perspectives and ideas I've found inspiring and resourceful. May this help you grow, enjoy! :)"
url:                 http://hubert.world
baseurl:             ''
paginate:            5
gems: ["jekyll-paginate"]

# About/contact
author:
  name:              Hubert World
  url:               https://twitter.com/hubertdotworld
  email:             hubertdotworld@gmail.com

# Custom vars
version:             1.0.0
